name: Mabl Automation Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-mabl-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Trigger Mabl Plan
        run: |
          curl -X POST https://api.mabl.com/v1/runs \
          -H "Authorization: API_KEY ${{ secrets.MABL_API_KEY }}" \
          -d '{ "planId": "reg-plan-001" }'
